package View;

import DAO.ReceitaDAO;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Receita;
/**
 *
 * @author Marcus 31/12/2022
 */
public class Tela_Cadastrar_Receita extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastrar_Receita
     */
    public Tela_Cadastrar_Receita() {
        initComponents();
        this.setLocationRelativeTo(null); //para a tela iniciar ao centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_Editar_Usuario = new javax.swing.JLabel();
        labelNomeReceita = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldCadastrarDataReceita = new javax.swing.JTextField();
        btnCadastrarReceita = new javax.swing.JButton();
        labelDataReceita = new javax.swing.JLabel();
        fieldCadastrarDetalheReceita = new javax.swing.JTextField();
        fieldCadastrarNomeReceita = new javax.swing.JTextField();
        labelDetalheReceita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_Editar_Usuario.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Titulo_Editar_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo_Editar_Usuario.setText("CADASTRAR RECEITA");
        getContentPane().add(Titulo_Editar_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 700, -1));

        labelNomeReceita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNomeReceita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeReceita.setText("Nome");
        getContentPane().add(labelNomeReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 450, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("@marcusvictor_sc");

        fieldCadastrarDataReceita.setEditable(false);
        fieldCadastrarDataReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCadastrarDataReceitaActionPerformed(evt);
            }
        });
        fieldCadastrarDataReceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCadastrarDataReceitaKeyPressed(evt);
            }
        });

        btnCadastrarReceita.setBackground(new java.awt.Color(51, 153, 0));
        btnCadastrarReceita.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarReceita.setText("Cadastrar");
        btnCadastrarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarReceitaActionPerformed(evt);
            }
        });
        btnCadastrarReceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarReceitaKeyPressed(evt);
            }
        });

        labelDataReceita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDataReceita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDataReceita.setText("Data");

        fieldCadastrarDetalheReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCadastrarDetalheReceitaActionPerformed(evt);
            }
        });
        fieldCadastrarDetalheReceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCadastrarDetalheReceitaKeyPressed(evt);
            }
        });

        fieldCadastrarNomeReceita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldCadastrarNomeReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCadastrarNomeReceitaActionPerformed(evt);
            }
        });
        fieldCadastrarNomeReceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCadastrarNomeReceitaKeyPressed(evt);
            }
        });

        labelDetalheReceita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDetalheReceita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDetalheReceita.setText("Detalhe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldCadastrarNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCadastrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldCadastrarDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldCadastrarDetalheReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataReceita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDetalheReceita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(fieldCadastrarNomeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(labelDetalheReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCadastrarDetalheReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDataReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCadastrarDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCadastrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(61, 61, 61))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 450, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCadastrarNomeReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCadastrarNomeReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCadastrarNomeReceitaActionPerformed

    private void fieldCadastrarDataReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCadastrarDataReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCadastrarDataReceitaActionPerformed

    private void btnCadastrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarReceitaActionPerformed
        

            String nome;
            String detalhe;
            String data;

            Tela_Cadastrar_Receita tela = new Tela_Cadastrar_Receita();

            nome = fieldCadastrarNomeReceita.getText();
            detalhe = fieldCadastrarDetalheReceita.getText();
            data = fieldCadastrarDataReceita.getText();

            Receita receita = new Receita();
            receita.setNome(nome);
            receita.setDetalhe(detalhe);
            receita.setData(data);

            if(fieldCadastrarDataReceita.getText().equals("") || fieldCadastrarNomeReceita.getText().equals("") || fieldCadastrarDetalheReceita.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }else{
                
            ReceitaDAO receitaDAO = new ReceitaDAO();
            receitaDAO.inserir(receita);
            
            dispose();
        }
        
        
    }//GEN-LAST:event_btnCadastrarReceitaActionPerformed

    private void fieldCadastrarNomeReceitaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCadastrarNomeReceitaKeyPressed
        //Direcionar o foco para outro campo de texto ao pressionar a tecla enter.
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldCadastrarDetalheReceita.requestFocus();
        }
    }//GEN-LAST:event_fieldCadastrarNomeReceitaKeyPressed

    private void fieldCadastrarDataReceitaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCadastrarDataReceitaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnCadastrarReceita.requestFocus();
        }
    }//GEN-LAST:event_fieldCadastrarDataReceitaKeyPressed

    private void btnCadastrarReceitaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarReceitaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String nome;
            String detalhe;
            String data;

            Tela_Cadastrar_Receita tela = new Tela_Cadastrar_Receita();

            nome = fieldCadastrarNomeReceita.getText();
            detalhe = fieldCadastrarDetalheReceita.getText();
            data = fieldCadastrarDataReceita.getText();

            Receita receita = new Receita();
            receita.setNome(nome);
            receita.setDetalhe(detalhe);
            receita.setData(data);

            if(fieldCadastrarDataReceita.getText().equals("") || fieldCadastrarNomeReceita.getText().equals("") || fieldCadastrarDetalheReceita.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            }else{
                
            ReceitaDAO receitaDAO = new ReceitaDAO();
            receitaDAO.inserir(receita);
            
            dispose();
        }
        }
    }//GEN-LAST:event_btnCadastrarReceitaKeyPressed

    private void fieldCadastrarDetalheReceitaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCadastrarDetalheReceitaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldCadastrarDataReceita.requestFocus();
        }
    }//GEN-LAST:event_fieldCadastrarDetalheReceitaKeyPressed

    private void fieldCadastrarDetalheReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCadastrarDetalheReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCadastrarDetalheReceitaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Aqui estou pegando a data do sistema, formatando e setando no campo data.
        Date data = new Date();
        DateFormat formatar = DateFormat.getDateInstance(DateFormat.DATE_FIELD);
        fieldCadastrarDataReceita.setText(formatar.format(data));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastrar_Receita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastrar_Receita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo_Editar_Usuario;
    private javax.swing.JButton btnCadastrarReceita;
    private javax.swing.JTextField fieldCadastrarDataReceita;
    private javax.swing.JTextField fieldCadastrarDetalheReceita;
    private javax.swing.JTextField fieldCadastrarNomeReceita;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDataReceita;
    private javax.swing.JLabel labelDetalheReceita;
    private javax.swing.JLabel labelNomeReceita;
    // End of variables declaration//GEN-END:variables

    

}
