package View;

import DAO.UsuarioDAO;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JTextField;
import model.Usuario;
/**
 *
 * @author Marcus 31/12/2022
 */
public class Tela_Cadastro_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cadastro_Usuario
     */
    public Tela_Cadastro_Usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_Cadastro_Usuario = new javax.swing.JLabel();
        labelNomeCadastro1 = new javax.swing.JLabel();
        labelNomeCadastro2 = new javax.swing.JLabel();
        labelNomeCadastro3 = new javax.swing.JLabel();
        fieldCadastrarNomeUsuario = new javax.swing.JTextField();
        fieldCadastrarEmailUsuario = new javax.swing.JTextField();
        fieldCadastrarSenhaUsuario = new javax.swing.JTextField();
        btnCadastrarUsuario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo_Cadastro_Usuario.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Titulo_Cadastro_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo_Cadastro_Usuario.setText("CADASTRO DE USUÁRIO");
        getContentPane().add(Titulo_Cadastro_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 700, -1));

        labelNomeCadastro1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNomeCadastro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeCadastro1.setText("Nome");
        getContentPane().add(labelNomeCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 193, 700, -1));

        labelNomeCadastro2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNomeCadastro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeCadastro2.setText("Senha");
        getContentPane().add(labelNomeCadastro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 404, 700, -1));

        labelNomeCadastro3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNomeCadastro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeCadastro3.setText("Email");
        getContentPane().add(labelNomeCadastro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 297, 700, -1));

        fieldCadastrarNomeUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCadastrarNomeUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(fieldCadastrarNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 240, 336, 30));

        fieldCadastrarEmailUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCadastrarEmailUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(fieldCadastrarEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 340, 336, 30));

        fieldCadastrarSenhaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldCadastrarSenhaUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(fieldCadastrarSenhaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 447, 336, 30));

        btnCadastrarUsuario.setBackground(new java.awt.Color(51, 153, 0));
        btnCadastrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarUsuario.setText("Cadastrar");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });
        btnCadastrarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(btnCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 520, 336, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("@marcusvictor_sc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(622, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(61, 61, 61))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 440, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        
        String nome;
        String email;
        String senha;
        
       // pegar dados informados nos campos de texto e salvar nas variáveis
        nome = fieldCadastrarNomeUsuario.getText();
        email = fieldCadastrarEmailUsuario.getText();
        senha = fieldCadastrarSenhaUsuario.getText();
        
        // inserir dados das variaveis ao objeto usuário
        Usuario usuario = new Usuario();
        usuario.setNome(nome);
        usuario.setEmail(email);
        usuario.setSenha(senha);
        
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.inserir(usuario);
        
        
        dispose();
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void fieldCadastrarNomeUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCadastrarNomeUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldCadastrarEmailUsuario.requestFocus();
        }
    }//GEN-LAST:event_fieldCadastrarNomeUsuarioKeyPressed

    private void fieldCadastrarEmailUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCadastrarEmailUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            fieldCadastrarSenhaUsuario.requestFocus();
        }
    }//GEN-LAST:event_fieldCadastrarEmailUsuarioKeyPressed

    private void fieldCadastrarSenhaUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCadastrarSenhaUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnCadastrarUsuario.requestFocus();
        }
    }//GEN-LAST:event_fieldCadastrarSenhaUsuarioKeyPressed

    private void btnCadastrarUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

        String nome;
        String email;
        String senha;
        
       // pegar dados informados nos campos de texto e salvar nas variáveis
        nome = fieldCadastrarNomeUsuario.getText();
        email = fieldCadastrarEmailUsuario.getText();
        senha = fieldCadastrarSenhaUsuario.getText();
        
        // inserir dados das variaveis ao objeto usuário
        Usuario usuario = new Usuario();
        usuario.setNome(nome);
        usuario.setEmail(email);
        usuario.setSenha(senha);
        
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.inserir(usuario);
        
        
        dispose();
        }
    }//GEN-LAST:event_btnCadastrarUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cadastro_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cadastro_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo_Cadastro_Usuario;
    private javax.swing.JButton btnCadastrarUsuario;
    private javax.swing.JTextField fieldCadastrarEmailUsuario;
    private javax.swing.JTextField fieldCadastrarNomeUsuario;
    private javax.swing.JTextField fieldCadastrarSenhaUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNomeCadastro1;
    private javax.swing.JLabel labelNomeCadastro2;
    private javax.swing.JLabel labelNomeCadastro3;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCadastrarUsuario() {
        return btnCadastrarUsuario;
    }

    public void setBtnCadastrarUsuario(JButton btnCadastrarUsuario) {
        this.btnCadastrarUsuario = btnCadastrarUsuario;
    }

    public JTextField getFieldCadastrarEmailUsuario() {
        return fieldCadastrarEmailUsuario;
    }

    public void setFieldCadastrarEmailUsuario(JTextField fieldCadastrarEmailUsuario) {
        this.fieldCadastrarEmailUsuario = fieldCadastrarEmailUsuario;
    }

    public JTextField getFieldCadastrarNomeUsuario() {
        return fieldCadastrarNomeUsuario;
    }

    public void setFieldCadastrarNomeUsuario(JTextField fieldCadastrarNomeUsuario) {
        this.fieldCadastrarNomeUsuario = fieldCadastrarNomeUsuario;
    }

    public JTextField getFieldCadastrarSenhaUsuario() {
        return fieldCadastrarSenhaUsuario;
    }

    public void setFieldCadastrarSenhaUsuario(JTextField fieldCadastrarSenhaUsuario) {
        this.fieldCadastrarSenhaUsuario = fieldCadastrarSenhaUsuario;
    }

    

}
