package View;

import DAO.ReceitaDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Receita;
/**
 *
 * @author Marcus 02/01/2023
 */
public class Tela_Receitas extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Receitas
     */
    public Tela_Receitas() {
        initComponents();
        this.setLocationRelativeTo(null);
        listar();
        tamanhoColunas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaReceitas = new javax.swing.JTable();
        btnExcluirReceitas = new javax.swing.JButton();
        btnEditarReceitas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNomeVisualizar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDetalhesVisualizar = new javax.swing.JTextArea();
        btnVisualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fieldIdReceitas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldDataReceitas = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RECEITAS");

        tabelaReceitas.setBackground(new java.awt.Color(204, 204, 204));
        tabelaReceitas.setBorder(new javax.swing.border.MatteBorder(null));
        tabelaReceitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Detalhes", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaReceitas.setRowHeight(20);
        tabelaReceitas.setRowSelectionAllowed(false);
        tabelaReceitas.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaReceitas);

        btnExcluirReceitas.setBackground(new java.awt.Color(255, 0, 51));
        btnExcluirReceitas.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirReceitas.setText("Excluír");
        btnExcluirReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirReceitasActionPerformed(evt);
            }
        });

        btnEditarReceitas.setBackground(new java.awt.Color(0, 0, 255));
        btnEditarReceitas.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarReceitas.setText("Editar");
        btnEditarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarReceitasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("@marcusvictor_sc");

        jLabel3.setText("Nome:");

        fieldNomeVisualizar.setEditable(false);
        fieldNomeVisualizar.setBackground(new java.awt.Color(204, 204, 204));
        fieldNomeVisualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setText("Detalhes:");

        textAreaDetalhesVisualizar.setEditable(false);
        textAreaDetalhesVisualizar.setBackground(new java.awt.Color(204, 204, 204));
        textAreaDetalhesVisualizar.setColumns(20);
        textAreaDetalhesVisualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textAreaDetalhesVisualizar.setRows(5);
        jScrollPane1.setViewportView(textAreaDetalhesVisualizar);

        btnVisualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        jLabel5.setText("Id");

        fieldIdReceitas.setEditable(false);
        fieldIdReceitas.setBackground(new java.awt.Color(204, 204, 204));
        fieldIdReceitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel6.setText("Data");

        fieldDataReceitas.setEditable(false);
        fieldDataReceitas.setBackground(new java.awt.Color(204, 204, 204));
        fieldDataReceitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnAlterar.setBackground(new java.awt.Color(0, 153, 0));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Salvar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addComponent(fieldNomeVisualizar)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditarReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVisualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldIdReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(fieldDataReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarReceitas)
                    .addComponent(btnVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIdReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldDataReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNomeVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnLimpar)
                    .addComponent(btnExcluirReceitas))
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarReceitasActionPerformed
        enviarCamposParaEditar();

    }//GEN-LAST:event_btnEditarReceitasActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        visualizar();

    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarFuncionario();
        listar();
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirReceitasActionPerformed
        deletar();
        listar();
        limparCampos();
    }//GEN-LAST:event_btnExcluirReceitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Receitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Receitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnEditarReceitas;
    private javax.swing.JButton btnExcluirReceitas;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JTextField fieldDataReceitas;
    private javax.swing.JTextField fieldIdReceitas;
    private javax.swing.JTextField fieldNomeVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaReceitas;
    private javax.swing.JTextArea textAreaDetalhesVisualizar;
    // End of variables declaration//GEN-END:variables

    protected void tamanhoColunas() {

        tabelaReceitas.setAutoResizeMode(tabelaReceitas.AUTO_RESIZE_OFF);
        //alerar o tamanho das colunas
        tabelaReceitas.getColumnModel().getColumn(0).setPreferredWidth(35);
        tabelaReceitas.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaReceitas.getColumnModel().getColumn(2).setPreferredWidth(315);
        tabelaReceitas.getColumnModel().getColumn(3).setPreferredWidth(100);

    }
    
    protected void limparCampos(){
        
        fieldIdReceitas.setText("");
        fieldNomeVisualizar.setText("");
        textAreaDetalhesVisualizar.setText("");
        fieldDataReceitas.setText("");
        
    }

    protected void listar() {

        try {
            ReceitaDAO receitaDAO = new ReceitaDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaReceitas.getModel();

            model.setNumRows(0);

            ArrayList<Receita> lista = receitaDAO.listar();

            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object[]{
                    lista.get(i).getIdReceita(),
                    lista.get(i).getNome(),
                    lista.get(i).getDetalhe(),
                    lista.get(i).getData()
                });
            }

        } catch (Exception e) {
        }
    }

    protected void visualizar() {

        //saber qual a linha da tabela que esta sendo selecionada
        int linha = tabelaReceitas.getSelectedRow();

        fieldIdReceitas.setText(tabelaReceitas.getModel().getValueAt(linha, 0).toString());
        fieldNomeVisualizar.setText(tabelaReceitas.getModel().getValueAt(linha, 1).toString());
        textAreaDetalhesVisualizar.setText(tabelaReceitas.getModel().getValueAt(linha, 2).toString());
        fieldDataReceitas.setText(tabelaReceitas.getModel().getValueAt(linha, 3).toString());

        fieldIdReceitas.setEditable(false);
        fieldNomeVisualizar.setEditable(false);
        textAreaDetalhesVisualizar.setEditable(false);
        fieldDataReceitas.setEditable(false);

    }

    protected void enviarCamposParaEditar() {

        int linha = tabelaReceitas.getSelectedRow();

        fieldIdReceitas.setEditable(false);
        fieldNomeVisualizar.setEditable(true);
        textAreaDetalhesVisualizar.setEditable(true);
        fieldDataReceitas.setEditable(true);

        fieldIdReceitas.setText(tabelaReceitas.getModel().getValueAt(linha, 0).toString());
        fieldNomeVisualizar.setText(tabelaReceitas.getModel().getValueAt(linha, 1).toString());
        textAreaDetalhesVisualizar.setText(tabelaReceitas.getModel().getValueAt(linha, 2).toString());
        fieldDataReceitas.setText(tabelaReceitas.getModel().getValueAt(linha, 3).toString());

    }

    private void alterarFuncionario() {

        int id;
        String nome;
        String detalhe;
        String data;

        id = Integer.parseInt(fieldIdReceitas.getText());
        nome = fieldNomeVisualizar.getText();
        detalhe = textAreaDetalhesVisualizar.getText();
        data = fieldDataReceitas.getText();

        Receita receita = new Receita();
        receita.setIdReceita(id);
        receita.setNome(nome);
        receita.setDetalhe(detalhe);
        receita.setData(data);

        ReceitaDAO receitaDAO = new ReceitaDAO();
        receitaDAO.alterar(receita);

    }
    
    private void deletar(){
        
        int id;
        
        id = Integer.parseInt(fieldIdReceitas.getText());
        
        Receita receita = new Receita();
        receita.setIdReceita(id);
        
        ReceitaDAO receitaDAO = new ReceitaDAO();
        receitaDAO.deletar(receita);
    }
}
