package View;
/**
 *
 * @author Marcus 02/01/2023
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        menuReceitas = new javax.swing.JMenu();
        itemReceitasVariadas = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        itemCadastrarUsuario = new javax.swing.JMenuItem();
        itemCadastrarReceita = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\projeto receitas\\img\\logo.jpg")); // NOI18N
        getContentPane().add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 0, -1, 680));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 700, 460));

        menuReceitas.setText("Receitas");

        itemReceitasVariadas.setBackground(new java.awt.Color(255, 255, 255));
        itemReceitasVariadas.setText("Variadas");
        itemReceitasVariadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReceitasVariadasActionPerformed(evt);
            }
        });
        menuReceitas.add(itemReceitasVariadas);

        menu.add(menuReceitas);

        menuCadastrar.setText("Cadastrar");

        itemCadastrarUsuario.setText("Usuário");
        itemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarUsuarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(itemCadastrarUsuario);

        itemCadastrarReceita.setText("Receita");
        itemCadastrarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarReceitaActionPerformed(evt);
            }
        });
        menuCadastrar.add(itemCadastrarReceita);

        menu.add(menuCadastrar);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarReceitaActionPerformed
        Tela_Cadastrar_Receita telaCadastrarReceita = new Tela_Cadastrar_Receita();
        telaCadastrarReceita.setVisible(true);
    }//GEN-LAST:event_itemCadastrarReceitaActionPerformed

    private void itemReceitasVariadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReceitasVariadasActionPerformed
        Tela_Receitas telaReceitas = new Tela_Receitas();
        telaReceitas.setVisible(true);
    }//GEN-LAST:event_itemReceitasVariadasActionPerformed

    private void itemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarUsuarioActionPerformed
        Tela_Cadastro_Usuario telaCadastrarUsuario = new Tela_Cadastro_Usuario();
        telaCadastrarUsuario.setVisible(true);
    }//GEN-LAST:event_itemCadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagem;
    private javax.swing.JMenuItem itemCadastrarReceita;
    private javax.swing.JMenuItem itemCadastrarUsuario;
    private javax.swing.JMenuItem itemReceitasVariadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuReceitas;
    // End of variables declaration//GEN-END:variables
}
